<<<<<<< HEAD:app/docker-compose.yml
version: "3.8"

services:
  postgres:
    image: postgres:latest
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}

volumes:
  postgresdb-data:
    driver: locals
=======
services:
  db:
      container_name: db
      image: postgres:14
      restart: always
      env_file:
        - .env
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        #PGDATA: "/var/lib/postgresql/data/pgdata"
      ports:
        - ${DB_PORT}:5432
      #volumes:
        # - ./cmd/internal/db/postgresql/schema/:/docker-entrypoint-initdb.d
        #- postgresdb-data:/var/lib/postgresql/data

#volumes:
#  postgresdb-data:
>>>>>>> af93f32 (stage):docker-compose.yml
